$(document).ready(function(){
  $('#Lbubble_red').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleRed.css";
  });
  $('#Lbubble_org').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleOrg.css";
  });
  $('#Lbubble_yel').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleYel.css";
  });
  $('#Lbubble_gre').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleGre.css";
  });
  $('#Lbubble_blu').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleBlu.css";
  });
  $('#Lbubble_whi').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleWhi.css";
  });
  $('#Lbubble_blk').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleBlk.css";
  });
  $('#Lbubble_gry').click((event)=>{
    event.preventDefault();
    Lbubblecolor.href="css/Lbubblecolor/LbubbleGry.css";
  });
});
