$(document).ready(function(){
  $('#Rbubble_red').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleRed.css";
  });
  $('#Rbubble_org').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleOrg.css";
  });
  $('#Rbubble_yel').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleYel.css";
  })
  $('#Rbubble_gre').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleGre.css";
  });
  $('#Rbubble_blu').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleBlu.css";
  });
  $('#Rbubble_whi').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleWhi.css";
  });
  $('#Rbubble_blk').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleBlk.css";
  });
  $('#Rbubble_gry').click((event)=>{
    event.preventDefault();
    Rbubblecolor.href="css/Rbubblecolor/RbubbleGry.css";
  });
});
